server {
    listen 80;
    root /var/www/html;
    index page51428489.html;

    location /data/ { deny all; return 404; }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
    }

    location = /policy       { rewrite ^ /page55196169.html last; }
    location = /remont-old   { rewrite ^ /page27262071.html last; }
    location = /quiz         { rewrite ^ /page55131289.html last; }
    location = /build        { rewrite ^ /page36631847.html last; }
    location = /remont       { rewrite ^ /page34319973.html last; }
    location = /remontdomov  { rewrite ^ /page34448363.html last; }
    location = /klinika      { rewrite ^ /page34448545.html last; }
    location = /engineering  { rewrite ^ /page27262068.html last; }
    location = /disign       { rewrite ^ /page27262073.html last; }
    location = /shtukaturka  { rewrite ^ /page30554334.html last; }
    location = /styajka      { rewrite ^ /page37346001.html last; }
    location = /pomesheniya  { rewrite ^ /page34448315.html last; }
    location = /stomatologiy { rewrite ^ /page34448619.html last; }
    location = /mebel        { rewrite ^ /page39349977.html last; }
    location = /portfolio    { rewrite ^ /page27262075.html last; }
    location = /about        { rewrite ^ /page27176351.html last; }
    location = /team         { rewrite ^ /page37551065.html last; }
    location = /thankyou     { rewrite ^ /page34361870.html last; }
    location = /remont2      { rewrite ^ /page37914626.html last; }
    location = /calculator   { rewrite ^ /page27262080.html last; }
    location = /vanna        { rewrite ^ /page34448199.html last; }
    location = /sanuzel      { rewrite ^ /page34448265.html last; }
    location = /kotedzh      { rewrite ^ /page34448395.html last; }
    location = /ofisov       { rewrite ^ /page34448443.html last; }
    location = /novostroika  { rewrite ^ /page34448501.html last; }
    location = /otdelka      { rewrite ^ /page34448654.html last; }
    location = /novostroika2 { rewrite ^ /page39375218.html last; }
    location = /buildtest    { rewrite ^ /page42625085.html last; }
    location = /quizstroy    { rewrite ^ /page55192735.html last; }
    location = /quizmebel    { rewrite ^ /page55193637.html last; }
    location = /agreement    { rewrite ^ /page90290286.html last; }
    location = /cookie-files { rewrite ^ /page90298606.html last; }

    location / { try_files $uri $uri/ =404; }

    error_page 404 /page52048683.html;
}
